///This will the constant List for dropdown item.
const List<String> ethnicity = [
  'Hispanic',
  'White alone, non-Hispanic',
  'Black or African American alone, non-Hispanic',
  'American Indian and Alaska Native alone, non-Hispanic',
  'Asian alone, non-Hispanic',
  'Native Hawaiian and Other Pacific Islander alone, non-Hispanic',
  'Some Other Race alone, non-Hispanic',
  'Multiracial, non-Hispanic',
];

const List<String> state = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];
const List<String> gender = [
  'Male',
  'Female',
  'Other',
];

const List<String> maritalStatus = [
  'Single',
  'Married',
  'Divorced',
  'Seperated',
];

List<String> insuranceProviders = [
  'Blue Cross Blue Shield',
  'United Healthcare',
  'HealthPartners',
  'Kaiser Foundation',
  'Anthem, Inc.',
  'Centene Corp',
  'Humana',
  'Molina Healthcare, Inc.',
  'CVS',
  'Independence Health Group',
  'HCSC',
  'Aetna',
  'Cigna Health',
  'Other',
];
